"""
Pydantic schemas for the Pagos module.
"""

from datetime import datetime
from decimal import Decimal
from typing import Optional
from pydantic import BaseModel, Field


# ─── Request Schemas ─────────────────────────────────────────────────────────

class PagoCreatePayload(BaseModel):
    """Payload from the frontend to initiate a payment for an order."""
    pedido_id: int
    token: str = Field(description="Card token generated by MercadoPago.js in the browser")
    installments: int = Field(default=1, ge=1, le=24)
    payment_method_id: str = Field(description="e.g. 'visa', 'master'")
    issuer_id: Optional[str] = Field(default=None)
    email: str = Field(description="Payer's email")


class PreferenciaCreatePayload(BaseModel):
    """Payload from frontend to create a MercadoPago Checkout Pro Preference."""
    pedido_id: int


class PreferenciaResponse(BaseModel):
    """Response containing the created preference details."""
    preference_id: str
    init_point: str
    idempotency_key: str



class WebhookPayload(BaseModel):
    """IPN/Webhook notification body from MercadoPago."""
    action: Optional[str] = None  # e.g. "payment.updated", "payment.created"
    api_version: Optional[str] = None
    data: Optional[dict] = None   # contains {"id": "mp_payment_id"}
    type: Optional[str] = None    # "payment"
    id: Optional[str] = None      # mp_payment_id for old IPN format


# ─── Response Schemas ─────────────────────────────────────────────────────────

class PagoResponse(BaseModel):
    id: int
    pedido_id: int
    monto: Decimal
    mp_payment_id: Optional[str]
    mp_status: Optional[str]
    estado: str
    idempotency_key: Optional[str]
    referencia_externa: Optional[str]
    created_at: datetime

    model_config = {"from_attributes": True}
