"""add_es_alergeno

Revision ID: 99300a852745
Revises: c079f7888238
Create Date: 2026-05-14 00:28:17.622458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99300a852745'
down_revision: Union[str, Sequence[str], None] = 'c079f7888238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('es_alergeno', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index('idx_productos_es_alergeno', 'productos', ['es_alergeno'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_productos_es_alergeno', table_name='productos')
    op.drop_column('productos', 'es_alergeno')
    # ### end Alembic commands ###
