"""initial_schema

Revision ID: c079f7888238
Revises: 
Create Date: 2026-05-13 22:42:57.612490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # required for sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = 'c079f7888238'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_categorias_activa', 'categorias', ['activa'], unique=False)
    op.create_index('idx_categorias_nombre', 'categorias', ['nombre'], unique=False)
    op.create_index('idx_categorias_parent_id', 'categorias', ['parent_id'], unique=False)
    op.create_index('idx_categorias_slug', 'categorias', ['slug'], unique=False)
    op.create_table('estados_pedido',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('es_final', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index('idx_estados_pedido_nombre', 'estados_pedido', ['nombre'], unique=False)
    op.create_table('formas_pago',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index('idx_formas_pago_nombre', 'formas_pago', ['nombre'], unique=False)
    op.create_table('ingredientes',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('es_alergeno', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index('idx_ingredientes_es_alergeno', 'ingredientes', ['es_alergeno'], unique=False)
    op.create_index('idx_ingredientes_nombre', 'ingredientes', ['nombre'], unique=False)
    op.create_table('productos',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('idx_productos_activo', 'productos', ['activo'], unique=False)
    op.create_index('idx_productos_nombre', 'productos', ['nombre'], unique=False)
    op.create_index('idx_productos_sku', 'productos', ['sku'], unique=False)
    op.create_table('roles',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index('idx_roles_nombre', 'roles', ['nombre'], unique=False)
    op.create_table('usuarios',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero_telefono', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('verificado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_usuarios_activo', 'usuarios', ['activo'], unique=False)
    op.create_index('idx_usuarios_email', 'usuarios', ['email'], unique=False)
    op.create_table('direcciones_entrega',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('departamento', sa.String(length=20), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('codigo_postal', sa.String(length=20), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('es_predeterminada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_direcciones_entrega_usuario_id', 'direcciones_entrega', ['usuario_id'], unique=False)
    op.create_table('productos_categorias',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_productos_categorias_producto_id_categoria_id', 'productos_categorias', ['producto_id', 'categoria_id'], unique=False)
    op.create_table('productos_ingredientes',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_productos_ingredientes_producto_id_ingrediente_id', 'productos_ingredientes', ['producto_id', 'ingrediente_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by_id', sa.Integer(), nullable=True),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_refresh_tokens_family_id', 'refresh_tokens', ['family_id'], unique=False)
    op.create_index('idx_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_refresh_tokens_usuario_id', 'refresh_tokens', ['usuario_id'], unique=False)
    op.create_table('usuario_roles',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usuario_roles_usuario_id_rol_id', 'usuario_roles', ['usuario_id', 'rol_id'], unique=False)
    op.create_table('pedidos',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('numero_pedido', sa.String(length=50), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('impuestos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_envio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('direccion_entrega_id', sa.Integer(), nullable=True),
    sa.Column('direccion_snapshot', sa.JSON(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['direccion_entrega_id'], ['direcciones_entrega.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estados_pedido.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_pedido')
    )
    op.create_index('idx_pedidos_estado_id', 'pedidos', ['estado_id'], unique=False)
    op.create_index('idx_pedidos_numero_pedido', 'pedidos', ['numero_pedido'], unique=False)
    op.create_index('idx_pedidos_usuario_id', 'pedidos', ['usuario_id'], unique=False)
    op.create_table('detalles_pedido',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('nombre_snapshot', sa.String(length=255), nullable=True),
    sa.Column('personalizacion', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_detalles_pedido_pedido_id', 'detalles_pedido', ['pedido_id'], unique=False)
    op.create_index('idx_detalles_pedido_producto_id', 'detalles_pedido', ['producto_id'], unique=False)
    op.create_table('historial_estados_pedido',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estados_pedido.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_historial_estados_pedido_estado_id', 'historial_estados_pedido', ['estado_id'], unique=False)
    op.create_index('idx_historial_estados_pedido_pedido_id', 'historial_estados_pedido', ['pedido_id'], unique=False)
    op.create_table('pagos',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('forma_pago_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('referencia_externa', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('mp_payment_id', sa.String(length=100), nullable=True),
    sa.Column('mp_status', sa.String(length=50), nullable=True),
    sa.Column('idempotency_key', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['forma_pago_id'], ['formas_pago.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_pagos_forma_pago_id', 'pagos', ['forma_pago_id'], unique=False)
    op.create_index('idx_pagos_mp_payment_id', 'pagos', ['mp_payment_id'], unique=False)
    op.create_index('idx_pagos_pedido_id', 'pagos', ['pedido_id'], unique=False)
    op.create_index('idx_pagos_referencia_externa', 'pagos', ['referencia_externa'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pagos_referencia_externa', table_name='pagos')
    op.drop_index('idx_pagos_pedido_id', table_name='pagos')
    op.drop_index('idx_pagos_mp_payment_id', table_name='pagos')
    op.drop_index('idx_pagos_forma_pago_id', table_name='pagos')
    op.drop_table('pagos')
    op.drop_index('idx_historial_estados_pedido_pedido_id', table_name='historial_estados_pedido')
    op.drop_index('idx_historial_estados_pedido_estado_id', table_name='historial_estados_pedido')
    op.drop_table('historial_estados_pedido')
    op.drop_index('idx_detalles_pedido_producto_id', table_name='detalles_pedido')
    op.drop_index('idx_detalles_pedido_pedido_id', table_name='detalles_pedido')
    op.drop_table('detalles_pedido')
    op.drop_index('idx_pedidos_usuario_id', table_name='pedidos')
    op.drop_index('idx_pedidos_numero_pedido', table_name='pedidos')
    op.drop_index('idx_pedidos_estado_id', table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index('idx_usuario_roles_usuario_id_rol_id', table_name='usuario_roles')
    op.drop_table('usuario_roles')
    op.drop_index('idx_refresh_tokens_usuario_id', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_family_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_productos_ingredientes_producto_id_ingrediente_id', table_name='productos_ingredientes')
    op.drop_table('productos_ingredientes')
    op.drop_index('idx_productos_categorias_producto_id_categoria_id', table_name='productos_categorias')
    op.drop_table('productos_categorias')
    op.drop_index('idx_direcciones_entrega_usuario_id', table_name='direcciones_entrega')
    op.drop_table('direcciones_entrega')
    op.drop_index('idx_usuarios_email', table_name='usuarios')
    op.drop_index('idx_usuarios_activo', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index('idx_roles_nombre', table_name='roles')
    op.drop_table('roles')
    op.drop_index('idx_productos_sku', table_name='productos')
    op.drop_index('idx_productos_nombre', table_name='productos')
    op.drop_index('idx_productos_activo', table_name='productos')
    op.drop_table('productos')
    op.drop_index('idx_ingredientes_nombre', table_name='ingredientes')
    op.drop_index('idx_ingredientes_es_alergeno', table_name='ingredientes')
    op.drop_table('ingredientes')
    op.drop_index('idx_formas_pago_nombre', table_name='formas_pago')
    op.drop_table('formas_pago')
    op.drop_index('idx_estados_pedido_nombre', table_name='estados_pedido')
    op.drop_table('estados_pedido')
    op.drop_index('idx_categorias_slug', table_name='categorias')
    op.drop_index('idx_categorias_parent_id', table_name='categorias')
    op.drop_index('idx_categorias_nombre', table_name='categorias')
    op.drop_index('idx_categorias_activa', table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
