"""add_cocina_role_and_product_availability

Revision ID: de9fb7255fbb
Revises: 99300a852745
Create Date: 2026-05-21 12:49:09.493215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9fb7255fbb'
down_revision: Union[str, Sequence[str], None] = '99300a852745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('disponible', sa.Boolean(), nullable=True))
    op.execute("UPDATE productos SET disponible = TRUE")
    op.alter_column('productos', 'disponible', nullable=False)
    op.create_index(op.f('ix_productos_disponible'), 'productos', ['disponible'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productos_disponible'), table_name='productos')
    op.drop_column('productos', 'disponible')
    # ### end Alembic commands ###
